<?php

namespace Database\Seeders;

use App\Models\FormTemplate;
use App\Models\FormTemplateField;
use Illuminate\Database\Seeder;

class FormTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // 1. Quality - Non-Conformance Report (NCR)
            [
                'name' => 'Non-Conformance Report (NCR)',
                'category' => 'Quality',
                'description' => 'Report and track non-conformances in processes, documents, equipment, or human error.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'NCR ID', 'name' => 'ncr_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Issue', 'name' => 'date_of_issue', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Department', 'name' => 'department'],
                    ['field_type' => 'text', 'label' => 'Process/Activity Involved', 'name' => 'process_activity_involved'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Non-Conformance', 'name' => 'type_of_non_conformance', 'options' => ['Process Deviation', 'Document Error', 'Equipment Fault', 'Human Error']],
                    ['field_type' => 'text', 'label' => 'Other (if applicable)', 'name' => 'type_other'],
                    ['field_type' => 'textarea', 'label' => 'Description', 'name' => 'description', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Date/Time of Occurrence', 'name' => 'date_time_occurrence'],
                    ['field_type' => 'select', 'label' => 'Detected During', 'name' => 'detected_during', 'options' => ['Audit', 'Routine Work', 'Inspection', 'Other']],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'select', 'label' => 'Severity Level', 'name' => 'severity_level', 'options' => ['Minor', 'Major', 'Critical']],
                    ['field_type' => 'radio', 'label' => 'Repeat Finding?', 'name' => 'repeat_finding', 'options' => ['Yes', 'No']],
                    ['field_type' => 'text', 'label' => 'Relevant Procedure/Standard', 'name' => 'relevant_procedure_standard'],
                ],
            ],
            // 2. Quality - Internal Audit Report
            [
                'name' => 'Internal Audit Report – Quality Department',
                'category' => 'Quality',
                'description' => 'Document internal audit findings and compliance status.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Audit ID', 'name' => 'audit_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Audit', 'name' => 'date_of_audit', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Auditor Name', 'name' => 'auditor_name', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Audited Department', 'name' => 'audited_department'],
                    ['field_type' => 'textarea', 'label' => 'Audit Scope', 'name' => 'audit_scope'],
                    ['field_type' => 'text', 'label' => 'Reference Standards / Manual / Procedure', 'name' => 'reference_standards'],
                    ['field_type' => 'textarea', 'label' => 'Findings Summary', 'name' => 'findings_summary'],
                    ['field_type' => 'radio', 'label' => 'Compliance Status', 'name' => 'compliance_status', 'options' => ['Compliant', 'Minor Non-Compliance', 'Major Non-Compliance', 'Observation']],
                    ['field_type' => 'textarea', 'label' => 'Non-Conformities (if any)', 'name' => 'non_conformities'],
                    ['field_type' => 'textarea', 'label' => 'Corrective Actions Recommended', 'name' => 'corrective_actions_recommended'],
                    ['field_type' => 'textarea', 'label' => 'Auditee Remarks', 'name' => 'auditee_remarks'],
                    ['field_type' => 'radio', 'label' => 'Follow-up Required', 'name' => 'follow_up_required', 'options' => ['Yes', 'No']],
                    ['field_type' => 'date', 'label' => 'Follow-up Date', 'name' => 'follow_up_date'],
                    ['field_type' => 'signature', 'label' => 'Auditor Signature', 'name' => 'auditor_signature'],
                    ['field_type' => 'signature', 'label' => 'Auditee Signature', 'name' => 'auditee_signature'],
                ],
            ],
            // 3. Quality - Quality Compliance Checklist
            [
                'name' => 'Quality Compliance Checklist – Quality Department',
                'category' => 'Quality',
                'description' => 'Checklist for reviewing procedure and process compliance.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Checklist ID', 'name' => 'checklist_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Review', 'name' => 'date_of_review', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Reviewer Name', 'name' => 'reviewer_name', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Department', 'name' => 'department'],
                    ['field_type' => 'text', 'label' => 'Procedure/Process Checked', 'name' => 'procedure_process_checked'],
                    ['field_type' => 'radio', 'label' => '1. Procedure up-to-date and followed', 'name' => 'item_1_procedure', 'options' => ['Yes', 'No', 'N/A']],
                    ['field_type' => 'text', 'label' => 'Item 1 Comments', 'name' => 'item_1_comments'],
                    ['field_type' => 'radio', 'label' => '2. Records maintained and traceable', 'name' => 'item_2_records', 'options' => ['Yes', 'No', 'N/A']],
                    ['field_type' => 'text', 'label' => 'Item 2 Comments', 'name' => 'item_2_comments'],
                    ['field_type' => 'radio', 'label' => '3. Staff trained and competent', 'name' => 'item_3_staff', 'options' => ['Yes', 'No', 'N/A']],
                    ['field_type' => 'text', 'label' => 'Item 3 Comments', 'name' => 'item_3_comments'],
                    ['field_type' => 'radio', 'label' => '4. Equipment/tools calibrated & functional', 'name' => 'item_4_equipment', 'options' => ['Yes', 'No', 'N/A']],
                    ['field_type' => 'text', 'label' => 'Item 4 Comments', 'name' => 'item_4_comments'],
                    ['field_type' => 'radio', 'label' => '5. Non-conformities managed appropriately', 'name' => 'item_5_non_conformities', 'options' => ['Yes', 'No', 'N/A']],
                    ['field_type' => 'text', 'label' => 'Item 5 Comments', 'name' => 'item_5_comments'],
                    ['field_type' => 'radio', 'label' => 'Compliance Summary', 'name' => 'compliance_summary', 'options' => ['Fully Compliant', 'Partially Compliant', 'Non-Compliant']],
                    ['field_type' => 'textarea', 'label' => 'Non-Compliances Noted', 'name' => 'non_compliances_noted'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Actions Taken', 'name' => 'immediate_actions_taken'],
                    ['field_type' => 'textarea', 'label' => 'Recommendations', 'name' => 'recommendations'],
                    ['field_type' => 'signature', 'label' => 'Reviewer Signature', 'name' => 'reviewer_signature'],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'review_date'],
                ],
            ],
            // 4. Quality - CAR/PAR Report
            [
                'name' => 'CAR/PAR Report (Corrective / Preventive Action)',
                'category' => 'Quality',
                'description' => 'Document corrective and preventive actions linked to NCRs.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'CAR/PAR ID', 'name' => 'car_par_id', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Linked to NCR ID (if any)', 'name' => 'linked_ncr_id'],
                    ['field_type' => 'date', 'label' => 'Date Issued', 'name' => 'date_issued', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Raised By', 'name' => 'raised_by', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Department', 'name' => 'department'],
                    ['field_type' => 'textarea', 'label' => 'Summary of Problem or Risk', 'name' => 'summary_of_problem', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Root Cause (RCA)', 'name' => 'root_cause', 'options' => ['Human Error', 'Equipment / Tool', 'Procedure Gap', 'Training Deficiency']],
                    ['field_type' => 'text', 'label' => 'Other Root Cause', 'name' => 'root_cause_other'],
                    ['field_type' => 'radio', 'label' => 'Type of Action', 'name' => 'type_of_action', 'options' => ['Corrective', 'Preventive']],
                    ['field_type' => 'textarea', 'label' => 'Description of Action(s)', 'name' => 'description_of_actions'],
                    ['field_type' => 'text', 'label' => 'Responsible Person', 'name' => 'responsible_person'],
                    ['field_type' => 'date', 'label' => 'Planned Completion Date', 'name' => 'planned_completion_date'],
                    ['field_type' => 'date', 'label' => 'Actual Completion Date', 'name' => 'actual_completion_date'],
                    ['field_type' => 'text', 'label' => 'Effectiveness Verified By', 'name' => 'effectiveness_verified_by'],
                    ['field_type' => 'date', 'label' => 'Date of Verification', 'name' => 'date_of_verification'],
                    ['field_type' => 'textarea', 'label' => 'Remarks on Effectiveness', 'name' => 'remarks_on_effectiveness'],
                ],
            ],
            // 5. MRO - Technical Defect Report
            [
                'name' => 'Technical Defect Report',
                'category' => 'MRO',
                'description' => 'Report technical defects for aircraft or components.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'TDR Number', 'name' => 'tdr_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Detection', 'name' => 'time_of_detection'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration / Component ID', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'ATA Chapter', 'name' => 'ata_chapter', 'placeholder' => 'e.g., 27 – Flight Controls'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location', 'placeholder' => 'Line / Hangar / Workshop, etc.'],
                    ['field_type' => 'select', 'label' => 'Detected During', 'name' => 'detected_during', 'options' => ['Scheduled Check', 'Routine Inspection', 'Troubleshooting', 'Operation']],
                    ['field_type' => 'textarea', 'label' => 'Defect Description', 'name' => 'defect_description', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Defect Severity', 'name' => 'defect_severity', 'options' => ['Minor', 'Major', 'Critical']],
                    ['field_type' => 'select', 'label' => 'Impact on Operations', 'name' => 'impact_on_operations', 'options' => ['AOG', 'Delayed', 'No impact']],
                    ['field_type' => 'radio', 'label' => 'Photos / Attachments', 'name' => 'photos_attachments', 'options' => ['Y', 'N']],
                    ['field_type' => 'textarea', 'label' => 'Initial Action Taken', 'name' => 'initial_action_taken'],
                    ['field_type' => 'textarea', 'label' => 'Corrective Action Required', 'name' => 'corrective_action_required'],
                    ['field_type' => 'text', 'label' => 'Work Order / Job Card Reference', 'name' => 'work_order_reference'],
                    ['field_type' => 'signature', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'signature', 'label' => 'Approved By', 'name' => 'approved_by'],
                    ['field_type' => 'date', 'label' => 'Date of Closure', 'name' => 'date_of_closure'],
                ],
            ],
            // 6. MRO - MEL Usage & Control Form
            [
                'name' => 'MEL Usage & Control Form',
                'category' => 'MRO',
                'description' => 'Track MEL deferrals and extensions.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'MEL Item Ref.', 'name' => 'mel_item_ref', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date Deferred', 'name' => 'date_deferred', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Deferral Category', 'name' => 'deferral_category', 'options' => ['A', 'B', 'C', 'D']],
                    ['field_type' => 'date', 'label' => 'Rectification Due Date', 'name' => 'rectification_due_date'],
                    ['field_type' => 'textarea', 'label' => 'Actions Taken', 'name' => 'actions_taken'],
                    ['field_type' => 'signature', 'label' => 'AME Signature', 'name' => 'ame_signature'],
                    ['field_type' => 'radio', 'label' => 'Extension Requested?', 'name' => 'extension_requested', 'options' => ['Yes', 'No']],
                ],
            ],
            // 7. MRO - Scheduled Maintenance Audit
            [
                'name' => 'Scheduled Maintenance Audit',
                'category' => 'MRO',
                'description' => 'Audit scheduled maintenance work packages.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Audit ID', 'name' => 'audit_id', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Maintenance Type', 'name' => 'maintenance_type', 'options' => ['A-Check', 'C-Check', 'B-Check', 'D-Check', 'Other']],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'audit_date', 'required' => true],
                    ['field_type' => 'textarea', 'label' => 'Work Packages Reviewed', 'name' => 'work_packages_reviewed'],
                    ['field_type' => 'textarea', 'label' => 'Deviations Observed', 'name' => 'deviations_observed'],
                    ['field_type' => 'select', 'label' => 'Compliance Status', 'name' => 'compliance_status', 'options' => ['Compliant', 'Partial', 'Non-compliant']],
                    ['field_type' => 'textarea', 'label' => 'Corrective Actions', 'name' => 'corrective_actions'],
                    ['field_type' => 'text', 'label' => 'Auditor Name', 'name' => 'auditor_name'],
                ],
            ],
            // 8. MRO - Manpower Utilization Report
            [
                'name' => 'Manpower Utilization Report',
                'category' => 'MRO',
                'description' => 'Track technician utilization and work completion.',
                'fields' => [
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'report_date', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Shift', 'name' => 'shift', 'options' => ['Day', 'Night']],
                    ['field_type' => 'select', 'label' => 'Section', 'name' => 'section', 'options' => ['Avionics', 'Structures', 'Engines', 'Other']],
                    ['field_type' => 'text', 'label' => 'Assigned Technicians', 'name' => 'assigned_technicians'],
                    ['field_type' => 'number', 'label' => 'Total Hours Worked', 'name' => 'total_hours_worked'],
                    ['field_type' => 'number', 'label' => 'Work Orders Completed', 'name' => 'work_orders_completed'],
                    ['field_type' => 'text', 'label' => 'Idle Time Logged', 'name' => 'idle_time_logged'],
                    ['field_type' => 'textarea', 'label' => 'Supervisor Comments', 'name' => 'supervisor_comments'],
                ],
            ],
            // === MRO SAFETY FORMS ===
            [
                'name' => 'Hazard Identification Report',
                'category' => 'MRO Safety',
                'description' => 'Identify and document workplace hazards.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Hazard ID', 'name' => 'hazard_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date Identified', 'name' => 'date_identified', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'textarea', 'label' => 'Hazard Description', 'name' => 'hazard_description', 'required' => true],
                    ['field_type' => 'textarea', 'label' => 'Potential Consequences', 'name' => 'potential_consequences'],
                    ['field_type' => 'select', 'label' => 'Risk Level (Pre-Mitigation)', 'name' => 'risk_level', 'options' => ['Low', 'Medium', 'High', 'Critical']],
                    ['field_type' => 'textarea', 'label' => 'Suggested Mitigation', 'name' => 'suggested_mitigation'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'text', 'label' => 'Person Reporting', 'name' => 'person_reporting'],
                    ['field_type' => 'text', 'label' => 'Department', 'name' => 'department'],
                    ['field_type' => 'textarea', 'label' => 'Supervisor Review Comments', 'name' => 'supervisor_review_comments'],
                    ['field_type' => 'signature', 'label' => 'Supervisor Signature', 'name' => 'supervisor_signature'],
                ],
            ],
            [
                'name' => 'Safety Investigation Template',
                'category' => 'MRO Safety',
                'description' => 'Template for conducting safety investigations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Investigation ID', 'name' => 'investigation_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date Opened', 'name' => 'date_opened', 'required' => true],
                    ['field_type' => 'textarea', 'label' => 'Event Summary', 'name' => 'event_summary'],
                    ['field_type' => 'textarea', 'label' => 'Timeline of Events Chronology', 'name' => 'timeline_of_events'],
                    ['field_type' => 'text', 'label' => 'Involved Personnel', 'name' => 'involved_personnel'],
                    ['field_type' => 'textarea', 'label' => 'Contributing Factors', 'name' => 'contributing_factors'],
                    ['field_type' => 'textarea', 'label' => 'Root Cause', 'name' => 'root_cause'],
                    ['field_type' => 'textarea', 'label' => 'Evidence Collected (Docs / Photos)', 'name' => 'evidence_collected'],
                    ['field_type' => 'textarea', 'label' => 'Safety Recommendations', 'name' => 'safety_recommendations'],
                    ['field_type' => 'radio', 'label' => 'CAPA Linked?', 'name' => 'capa_linked', 'options' => ['Yes', 'No']],
                    ['field_type' => 'text', 'label' => 'Investigator Name', 'name' => 'investigator_name'],
                    ['field_type' => 'date', 'label' => 'Report Closure Date', 'name' => 'report_closure_date'],
                ],
            ],
            [
                'name' => 'Maintenance Safety Report (MRO)',
                'category' => 'MRO Safety',
                'description' => 'Report maintenance-related safety incidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report Number', 'name' => 'report_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Incident', 'name' => 'time_of_incident'],
                    ['field_type' => 'select', 'label' => 'Location', 'name' => 'location', 'options' => ['Hangar', 'Line', 'Workshop', 'Other']],
                    ['field_type' => 'select', 'label' => 'Shift', 'name' => 'shift', 'options' => ['Day', 'Night']],
                    ['field_type' => 'text', 'label' => 'Personnel Involved (Names, roles)', 'name' => 'personnel_involved'],
                    ['field_type' => 'textarea', 'label' => 'Description of Incident', 'name' => 'incident_description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Injuries?', 'name' => 'injuries', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Injury Details (if yes)', 'name' => 'injury_details'],
                    ['field_type' => 'text', 'label' => 'Equipment Involved', 'name' => 'equipment_involved'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'textarea', 'label' => 'Contributing Factors', 'name' => 'contributing_factors', 'placeholder' => 'Human, Equipment, Procedure, etc.'],
                    ['field_type' => 'textarea', 'label' => 'Recommendations', 'name' => 'recommendations'],
                    ['field_type' => 'text', 'label' => 'Reported By (Name, Position)', 'name' => 'reported_by'],
                    ['field_type' => 'signature', 'label' => 'Signature', 'name' => 'signature'],
                ],
            ],
            [
                'name' => 'Incident / Accident Report',
                'category' => 'MRO Safety',
                'description' => 'Report incidents and accidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report Number', 'name' => 'report_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'report_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'report_time'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'select', 'label' => 'Nature of Incident', 'name' => 'nature_of_incident', 'options' => ['Near miss', 'Minor accident', 'Major accident']],
                    ['field_type' => 'textarea', 'label' => 'Description (Factual account)', 'name' => 'description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Photos / Evidence Attached', 'name' => 'photos_attached', 'options' => ['Y', 'N']],
                    ['field_type' => 'text', 'label' => 'Parties Involved', 'name' => 'parties_involved'],
                    ['field_type' => 'textarea', 'label' => 'Environmental Impact (if applicable)', 'name' => 'environmental_impact'],
                    ['field_type' => 'textarea', 'label' => 'Root Cause (if known)', 'name' => 'root_cause'],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'text', 'label' => 'Notified Authorities', 'name' => 'notified_authorities', 'placeholder' => 'Internal / External'],
                    ['field_type' => 'select', 'label' => 'Report Status', 'name' => 'report_status', 'options' => ['Open', 'Under Investigation', 'Closed']],
                ],
            ],
            // === MAINTENANCE FORMS ===
            [
                'name' => 'MEL Usage Report',
                'category' => 'Maintenance',
                'description' => 'Report MEL usage and deferrals.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'text', 'label' => 'Date/Time of MEL Use', 'name' => 'mel_use_datetime'],
                    ['field_type' => 'text', 'label' => 'MEL Item Reference', 'name' => 'mel_item_reference'],
                    ['field_type' => 'text', 'label' => 'ATA Chapter', 'name' => 'ata_chapter'],
                    ['field_type' => 'textarea', 'label' => 'Description of Item/System', 'name' => 'item_description'],
                    ['field_type' => 'select', 'label' => 'Category', 'name' => 'category', 'options' => ['A', 'B', 'C', 'D']],
                    ['field_type' => 'date', 'label' => 'Deferral Date', 'name' => 'deferral_date'],
                    ['field_type' => 'date', 'label' => 'Due Date', 'name' => 'due_date'],
                    ['field_type' => 'textarea', 'label' => 'Rectification Plan', 'name' => 'rectification_plan'],
                    ['field_type' => 'radio', 'label' => 'Special Procedures Applied', 'name' => 'special_procedures', 'options' => ['YES', 'NO']],
                    ['field_type' => 'textarea', 'label' => 'Special Procedures (if yes)', 'name' => 'special_procedures_detail'],
                    ['field_type' => 'textarea', 'label' => 'Remarks by Engineering or Maintenance Control', 'name' => 'remarks'],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'text', 'label' => 'Position/Dept', 'name' => 'position_dept'],
                ],
            ],
            [
                'name' => 'Maintenance Safety Report',
                'category' => 'Maintenance',
                'description' => 'Report maintenance safety issues and incidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Event', 'name' => 'time_of_event'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Maintenance Task Involved', 'name' => 'maintenance_task'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Safety Issue', 'name' => 'safety_issue_type', 'options' => ['Human Error', 'Tool/Equipment Misuse', 'Improper Documentation', 'Safety Procedure Violation', 'Near Miss']],
                    ['field_type' => 'text', 'label' => 'Other (if applicable)', 'name' => 'safety_issue_other'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description', 'name' => 'detailed_description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Fatigue / Time Pressure', 'name' => 'fatigue_time_pressure', 'options' => ['YES', 'NO']],
                    ['field_type' => 'radio', 'label' => 'Lack of Resources / Tools', 'name' => 'lack_resources', 'options' => ['YES', 'NO']],
                    ['field_type' => 'radio', 'label' => 'Training / Competence', 'name' => 'training_competence', 'options' => ['Adequate', 'Inadequate']],
                    ['field_type' => 'text', 'label' => 'Environmental Conditions', 'name' => 'environmental_conditions'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Actions Taken', 'name' => 'immediate_actions_taken'],
                    ['field_type' => 'textarea', 'label' => 'Corrective / Preventive Actions', 'name' => 'corrective_preventive_actions'],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'signature', 'label' => 'Supervisor Signature', 'name' => 'supervisor_signature'],
                ],
            ],
            [
                'name' => 'Scheduled Maintenance Audit Report',
                'category' => 'Maintenance',
                'description' => 'Audit report for scheduled maintenance tasks.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Audit ID', 'name' => 'audit_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Audit', 'name' => 'date_of_audit', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Auditor Name', 'name' => 'auditor_name'],
                    ['field_type' => 'text', 'label' => 'Audited By (Team/Company)', 'name' => 'audited_by'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Scheduled Maintenance Task(s)', 'name' => 'maintenance_tasks'],
                    ['field_type' => 'text', 'label' => 'Finding #1 Reference', 'name' => 'finding_1_reference'],
                    ['field_type' => 'textarea', 'label' => 'Finding #1 Description', 'name' => 'finding_1_description'],
                    ['field_type' => 'select', 'label' => 'Finding #1 Severity', 'name' => 'finding_1_severity', 'options' => ['Minor', 'Major', 'Critical']],
                    ['field_type' => 'textarea', 'label' => 'Finding #1 Corrective Action', 'name' => 'finding_1_corrective_action'],
                    ['field_type' => 'text', 'label' => 'Finding #2 Reference', 'name' => 'finding_2_reference'],
                    ['field_type' => 'textarea', 'label' => 'Finding #2 Description', 'name' => 'finding_2_description'],
                    ['field_type' => 'select', 'label' => 'Finding #2 Severity', 'name' => 'finding_2_severity', 'options' => ['Minor', 'Major', 'Critical']],
                    ['field_type' => 'textarea', 'label' => 'Finding #2 Corrective Action', 'name' => 'finding_2_corrective_action'],
                    ['field_type' => 'select', 'label' => 'Compliance Level', 'name' => 'compliance_level', 'options' => ['Compliant', 'Non-Compliant', 'Partial']],
                    ['field_type' => 'textarea', 'label' => 'Recommendations', 'name' => 'recommendations'],
                    ['field_type' => 'signature', 'label' => 'Auditor Signature', 'name' => 'auditor_signature'],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'audit_date'],
                ],
            ],
            // === SAFETY REPORTS ===
            [
                'name' => 'Corrective & Preventive Action (CAPA) Form',
                'category' => 'Safety',
                'description' => 'Document corrective and preventive actions.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'CAPA ID', 'name' => 'capa_id', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Linked Report/Event', 'name' => 'linked_report'],
                    ['field_type' => 'date', 'label' => 'Date Raised', 'name' => 'date_raised', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Raised By', 'name' => 'raised_by'],
                    ['field_type' => 'textarea', 'label' => 'Corrective Action', 'name' => 'corrective_action'],
                    ['field_type' => 'textarea', 'label' => 'Preventive Action (if needed)', 'name' => 'preventive_action'],
                    ['field_type' => 'text', 'label' => 'Responsible Person', 'name' => 'responsible_person'],
                    ['field_type' => 'date', 'label' => 'Target Date', 'name' => 'target_date'],
                    ['field_type' => 'date', 'label' => 'Completion Date', 'name' => 'completion_date'],
                    ['field_type' => 'text', 'label' => 'Effectiveness Verified By', 'name' => 'effectiveness_verified_by'],
                    ['field_type' => 'date', 'label' => 'Date Verified', 'name' => 'date_verified'],
                ],
            ],
            [
                'name' => 'Injury Report',
                'category' => 'Safety',
                'description' => 'Report workplace injuries.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Injury', 'name' => 'date_of_injury', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Injury', 'name' => 'time_of_injury'],
                    ['field_type' => 'text', 'label' => 'Injured Person\'s Name', 'name' => 'injured_person_name'],
                    ['field_type' => 'text', 'label' => 'Job Title / Department', 'name' => 'job_title_department'],
                    ['field_type' => 'text', 'label' => 'Location of Incident', 'name' => 'location'],
                    ['field_type' => 'textarea', 'label' => 'Activity Being Performed', 'name' => 'activity_performed'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Injury', 'name' => 'injury_type', 'options' => ['Cut', 'Sprain', 'Fracture', 'Burn']],
                    ['field_type' => 'text', 'label' => 'Other Injury Type', 'name' => 'injury_type_other'],
                    ['field_type' => 'text', 'label' => 'Body Part Affected', 'name' => 'body_part_affected'],
                    ['field_type' => 'radio', 'label' => 'Was First Aid Given?', 'name' => 'first_aid_given', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Was Emergency Care Needed?', 'name' => 'emergency_care_needed', 'options' => ['Yes', 'No']],
                ],
            ],
            [
                'name' => 'Occurrence Report',
                'category' => 'Safety',
                'description' => 'Report aviation occurrences and events.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Occurrence ID', 'name' => 'occurrence_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'occurrence_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'occurrence_time'],
                    ['field_type' => 'text', 'label' => 'Flight Number / Aircraft', 'name' => 'flight_number_aircraft'],
                    ['field_type' => 'text', 'label' => 'Location (Airport/Enroute)', 'name' => 'location'],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Occurrence', 'name' => 'occurrence_type', 'options' => ['ATC Related', 'Runway Incursion', 'System/Equipment Failure', 'Weather Related', 'Bird/Wildlife']],
                    ['field_type' => 'text', 'label' => 'Other Occurrence Type', 'name' => 'occurrence_type_other'],
                    ['field_type' => 'textarea', 'label' => 'Description', 'name' => 'description'],
                    ['field_type' => 'select', 'label' => 'Severity Assessment', 'name' => 'severity', 'options' => ['Minor', 'Major', 'Serious', 'Accident']],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                ],
            ],
            [
                'name' => 'Bird Strike Report',
                'category' => 'Safety',
                'description' => 'Report bird strike incidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'report_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'report_time'],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'select', 'label' => 'Phase of Flight', 'name' => 'phase_of_flight', 'options' => ['Takeoff', 'Climb', 'Cruise', 'Descent', 'Landing']],
                    ['field_type' => 'text', 'label' => 'Location (Runway/Altitude)', 'name' => 'location'],
                    ['field_type' => 'radio', 'label' => 'Was a Bird Strike Confirmed?', 'name' => 'bird_strike_confirmed', 'options' => ['Yes', 'No']],
                    ['field_type' => 'number', 'label' => 'Number of Birds Struck (approx.)', 'name' => 'birds_struck_count'],
                    ['field_type' => 'radio', 'label' => 'Damage to Aircraft?', 'name' => 'damage_to_aircraft', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Damage Description (if yes)', 'name' => 'damage_description'],
                    ['field_type' => 'text', 'label' => 'Bird Species (if known)', 'name' => 'bird_species'],
                ],
            ],
            [
                'name' => 'Safety Concern Report',
                'category' => 'Safety',
                'description' => 'Report safety concerns and near misses.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Concern', 'name' => 'date_of_concern', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'time_of_concern'],
                    ['field_type' => 'text', 'label' => 'Location/Area', 'name' => 'location'],
                    ['field_type' => 'text', 'label' => 'Reported By (Name & Dept)', 'name' => 'reported_by'],
                    ['field_type' => 'checkbox', 'label' => 'Nature of Concern', 'name' => 'nature_of_concern', 'options' => ['Unsafe Behavior', 'Unsafe Condition', 'Near Miss', 'Breach of Procedure']],
                    ['field_type' => 'text', 'label' => 'Other Nature', 'name' => 'nature_other'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description', 'name' => 'detailed_description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Risk Level (Initial Assessment)', 'name' => 'risk_level', 'options' => ['Low', 'Medium', 'High']],
                    ['field_type' => 'textarea', 'label' => 'Immediate Mitigation', 'name' => 'immediate_mitigation'],
                    ['field_type' => 'textarea', 'label' => 'Safety Officer Comments', 'name' => 'safety_officer_comments'],
                ],
            ],
            [
                'name' => 'Security Incident Report',
                'category' => 'Safety',
                'description' => 'Report security incidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'incident_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'incident_time'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Incident', 'name' => 'incident_type', 'options' => ['Unauthorized Access', 'Suspicious Behavior', 'Theft/Loss', 'Threat']],
                    ['field_type' => 'text', 'label' => 'Other Incident Type', 'name' => 'incident_type_other'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description', 'name' => 'detailed_description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Security Personnel Notified?', 'name' => 'security_notified', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                ],
            ],
            [
                'name' => 'Safety Investigation Form',
                'category' => 'Safety',
                'description' => 'Conduct safety investigations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Investigation ID', 'name' => 'investigation_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Occurrence', 'name' => 'date_of_occurrence', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Investigated By', 'name' => 'investigated_by'],
                    ['field_type' => 'text', 'label' => 'Related Report IDs', 'name' => 'related_report_ids'],
                    ['field_type' => 'textarea', 'label' => 'Event Summary', 'name' => 'event_summary'],
                    ['field_type' => 'textarea', 'label' => 'Timeline of Events', 'name' => 'timeline_of_events'],
                    ['field_type' => 'checkbox', 'label' => 'Contributing Factors', 'name' => 'contributing_factors', 'options' => ['Human', 'Technical', 'Environmental', 'Organizational']],
                    ['field_type' => 'textarea', 'label' => 'Findings', 'name' => 'findings'],
                    ['field_type' => 'textarea', 'label' => 'Root Cause Analysis', 'name' => 'root_cause_analysis'],
                ],
            ],
            [
                'name' => 'Risk Assessment Form',
                'category' => 'Safety',
                'description' => 'Assess and document risks.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Assessment ID', 'name' => 'assessment_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'assessment_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Assessed By', 'name' => 'assessed_by'],
                    ['field_type' => 'text', 'label' => 'Hazard/Issue Being Assessed', 'name' => 'hazard_issue'],
                    ['field_type' => 'select', 'label' => 'Likelihood', 'name' => 'likelihood', 'options' => ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost Certain']],
                    ['field_type' => 'select', 'label' => 'Severity', 'name' => 'severity', 'options' => ['Negligible', 'Minor', 'Major', 'Hazardous', 'Catastrophic']],
                    ['field_type' => 'select', 'label' => 'Initial Risk Rating', 'name' => 'initial_risk_rating', 'options' => ['Low', 'Med', 'High']],
                    ['field_type' => 'textarea', 'label' => 'Controls in Place', 'name' => 'controls_in_place'],
                    ['field_type' => 'select', 'label' => 'Residual Risk Rating', 'name' => 'residual_risk_rating', 'options' => ['Low', 'Med', 'High']],
                    ['field_type' => 'textarea', 'label' => 'Recommended Mitigations', 'name' => 'recommended_mitigations'],
                ],
            ],
            [
                'name' => 'Hazard Report',
                'category' => 'Safety',
                'description' => 'Report workplace hazards.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'text', 'label' => 'Reported By (Name & Position)', 'name' => 'reported_by'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Hazard', 'name' => 'hazard_type', 'options' => ['Operational', 'Environmental', 'Equipment', 'Human Factor']],
                    ['field_type' => 'text', 'label' => 'Other Hazard Type', 'name' => 'hazard_type_other'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description', 'name' => 'detailed_description', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Likelihood', 'name' => 'likelihood', 'options' => ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost Certain']],
                    ['field_type' => 'select', 'label' => 'Severity', 'name' => 'severity', 'options' => ['Negligible', 'Minor', 'Major', 'Hazardous', 'Catastrophic']],
                    ['field_type' => 'text', 'label' => 'Risk Level', 'name' => 'risk_level'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken (if any)', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'textarea', 'label' => 'Suggested Corrective/Preventive Action', 'name' => 'suggested_action'],
                    ['field_type' => 'textarea', 'label' => 'Safety Manager Review', 'name' => 'safety_manager_review'],
                    ['field_type' => 'date', 'label' => 'Date of Review', 'name' => 'date_of_review'],
                ],
            ],
            // === FLIGHT OPS ===
            [
                'name' => 'Line Check Report',
                'category' => 'Flight Ops',
                'description' => 'Document line check evaluations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Line Check Number', 'name' => 'line_check_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Check', 'name' => 'date_of_check', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Aircraft Type', 'name' => 'aircraft_type'],
                    ['field_type' => 'text', 'label' => 'Pilot Name', 'name' => 'pilot_name'],
                    ['field_type' => 'select', 'label' => 'Rank', 'name' => 'rank', 'options' => ['Captain', 'FO', 'Trainee']],
                    ['field_type' => 'textarea', 'label' => 'Flight Details (Route, duration)', 'name' => 'flight_details'],
                    ['field_type' => 'textarea', 'label' => 'Items Evaluated', 'name' => 'items_evaluated', 'placeholder' => 'Briefing, SOP adherence, Handling, CRM'],
                    ['field_type' => 'textarea', 'label' => 'Strengths Observed', 'name' => 'strengths_observed'],
                    ['field_type' => 'textarea', 'label' => 'Areas for Improvement', 'name' => 'areas_for_improvement'],
                    ['field_type' => 'select', 'label' => 'Overall Result', 'name' => 'overall_result', 'options' => ['Pass', 'Conditional', 'Fail']],
                    ['field_type' => 'textarea', 'label' => 'Remarks', 'name' => 'remarks'],
                    ['field_type' => 'text', 'label' => 'Checked By (Line Training Captain)', 'name' => 'checked_by'],
                    ['field_type' => 'signature', 'label' => 'Signature', 'name' => 'signature'],
                ],
            ],
            [
                'name' => 'Fatigue Report',
                'category' => 'Flight Ops',
                'description' => 'Report crew fatigue incidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report Number', 'name' => 'report_number', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Name of Crew Member', 'name' => 'crew_member_name'],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Date & Time of Duty', 'name' => 'duty_datetime'],
                    ['field_type' => 'textarea', 'label' => 'Flight/Duty Details', 'name' => 'flight_duty_details', 'placeholder' => 'Flight number, sectors, duration'],
                    ['field_type' => 'select', 'label' => 'Type of Fatigue', 'name' => 'fatigue_type', 'options' => ['Physical', 'Mental', 'Both']],
                    ['field_type' => 'textarea', 'label' => 'Symptoms Observed', 'name' => 'symptoms_observed', 'placeholder' => 'E.g. drowsiness, low alertness'],
                    ['field_type' => 'textarea', 'label' => 'Impact on Performance', 'name' => 'impact_on_performance'],
                    ['field_type' => 'radio', 'label' => 'Did You Take Countermeasures?', 'name' => 'countermeasures_taken', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Countermeasures Description', 'name' => 'countermeasures_description'],
                    ['field_type' => 'textarea', 'label' => 'Fatigue Contributing Factors', 'name' => 'contributing_factors', 'placeholder' => 'Sleep, Rostering, Delay, etc.'],
                    ['field_type' => 'textarea', 'label' => 'Additional Comments', 'name' => 'additional_comments'],
                    ['field_type' => 'signature', 'label' => 'Signature (Optional)', 'name' => 'signature'],
                ],
            ],
            [
                'name' => 'ASR – Aviation Safety Report',
                'category' => 'Flight Ops',
                'description' => 'Aviation safety reporting.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report Number', 'name' => 'report_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Occurrence', 'name' => 'date_of_occurrence', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Occurrence', 'name' => 'time_of_occurrence'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location', 'placeholder' => 'Airport, Enroute, etc.'],
                    ['field_type' => 'text', 'label' => 'Flight Number / Registration', 'name' => 'flight_number_registration'],
                    ['field_type' => 'text', 'label' => 'Aircraft Type', 'name' => 'aircraft_type'],
                    ['field_type' => 'select', 'label' => 'Phase of Flight', 'name' => 'phase_of_flight', 'options' => ['Taxi', 'Takeoff', 'Climb', 'Cruise', 'Descent', 'Landing']],
                    ['field_type' => 'textarea', 'label' => 'Description of Event', 'name' => 'event_description', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Persons Involved', 'name' => 'persons_involved', 'placeholder' => 'Crew/ATC/Passengers/etc.'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'textarea', 'label' => 'Contributing Factors', 'name' => 'contributing_factors', 'placeholder' => 'Weather, Human, Technical, etc.'],
                    ['field_type' => 'text', 'label' => 'Reporting Person Name', 'name' => 'reporting_person_name'],
                    ['field_type' => 'text', 'label' => 'Position / Department', 'name' => 'position_department'],
                    ['field_type' => 'date', 'label' => 'Date of Report Submission', 'name' => 'report_submission_date'],
                    ['field_type' => 'radio', 'label' => 'Confidential?', 'name' => 'confidential', 'options' => ['Y', 'N']],
                    ['field_type' => 'textarea', 'label' => 'Attachments (Photos, recordings, etc.)', 'name' => 'attachments'],
                ],
            ],
            [
                'name' => 'Route Check Report',
                'category' => 'Flight Ops',
                'description' => 'Document route check evaluations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Route Check Number', 'name' => 'route_check_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Check', 'name' => 'date_of_check', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Check Type', 'name' => 'check_type', 'options' => ['Initial', 'Recurrent', 'Upgrade']],
                    ['field_type' => 'text', 'label' => 'Aircraft Type', 'name' => 'aircraft_type'],
                    ['field_type' => 'text', 'label' => 'Flight Sector(s)', 'name' => 'flight_sectors'],
                    ['field_type' => 'text', 'label' => 'Pilot Name', 'name' => 'pilot_name'],
                    ['field_type' => 'text', 'label' => 'License No.', 'name' => 'license_no'],
                    ['field_type' => 'text', 'label' => 'Assessor Name', 'name' => 'assessor_name'],
                    ['field_type' => 'text', 'label' => 'Department', 'name' => 'department', 'placeholder' => 'Flight Operations'],
                    ['field_type' => 'textarea', 'label' => 'Areas Evaluated', 'name' => 'areas_evaluated', 'placeholder' => 'Preflight, Briefing, CRM, Technical Skill'],
                    ['field_type' => 'textarea', 'label' => 'Comments', 'name' => 'comments'],
                    ['field_type' => 'select', 'label' => 'Final Evaluation', 'name' => 'final_evaluation', 'options' => ['Satisfactory', 'Needs Improvement', 'Fail']],
                    ['field_type' => 'signature', 'label' => 'Assessor Signature', 'name' => 'assessor_signature'],
                    ['field_type' => 'signature', 'label' => 'Pilot Signature', 'name' => 'pilot_signature'],
                ],
            ],
            [
                'name' => 'Cabin Safety Report',
                'category' => 'Flight Ops',
                'description' => 'Report cabin safety events.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report Number', 'name' => 'report_number', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'date', 'label' => 'Date of Flight', 'name' => 'date_of_flight'],
                    ['field_type' => 'text', 'label' => 'Cabin Crew Name', 'name' => 'cabin_crew_name'],
                    ['field_type' => 'text', 'label' => 'Position', 'name' => 'position', 'placeholder' => 'e.g. L1, R2'],
                    ['field_type' => 'textarea', 'label' => 'Description of Event', 'name' => 'event_description'],
                    ['field_type' => 'radio', 'label' => 'Passenger(s) Involved?', 'name' => 'passengers_involved', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Passenger Details (if yes)', 'name' => 'passenger_details'],
                    ['field_type' => 'radio', 'label' => 'Injury Reported?', 'name' => 'injury_reported', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Injury Details (if yes)', 'name' => 'injury_details'],
                    ['field_type' => 'textarea', 'label' => 'Safety Equipment Issue', 'name' => 'safety_equipment_issue'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'radio', 'label' => 'Captain Notified?', 'name' => 'captain_notified', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Additional Notes', 'name' => 'additional_notes'],
                ],
            ],
            [
                'name' => 'FDM Deviation Report',
                'category' => 'Flight Ops',
                'description' => 'Report FDM events and deviations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'FDM Event ID', 'name' => 'fdm_event_id', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'date', 'label' => 'Date of Event', 'name' => 'date_of_event'],
                    ['field_type' => 'text', 'label' => 'Time of Event', 'name' => 'time_of_event'],
                    ['field_type' => 'text', 'label' => 'Event Type', 'name' => 'event_type', 'placeholder' => 'E.g. hard landing, unstabilized approach'],
                    ['field_type' => 'text', 'label' => 'Phase of Flight', 'name' => 'phase_of_flight'],
                    ['field_type' => 'textarea', 'label' => 'Event Summary', 'name' => 'event_summary'],
                    ['field_type' => 'text', 'label' => 'Parameters Triggered', 'name' => 'parameters_triggered', 'placeholder' => 'Pitch, G-Force, etc.'],
                    ['field_type' => 'textarea', 'label' => 'Crew Feedback', 'name' => 'crew_feedback'],
                    ['field_type' => 'radio', 'label' => 'Investigation Required?', 'name' => 'investigation_required', 'options' => ['Yes', 'No']],
                    ['field_type' => 'text', 'label' => 'Assigned To', 'name' => 'assigned_to'],
                    ['field_type' => 'select', 'label' => 'Status', 'name' => 'status', 'options' => ['Open', 'Under Review', 'Closed']],
                    ['field_type' => 'date', 'label' => 'Closure Date', 'name' => 'closure_date'],
                ],
            ],
            // === OCC FORMS ===
            [
                'name' => 'Crew Scheduling Concern Report',
                'category' => 'OCC',
                'description' => 'Report crew scheduling concerns and fatigue risks.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Crew Member Name', 'name' => 'crew_member_name'],
                    ['field_type' => 'text', 'label' => 'Crew ID / Position', 'name' => 'crew_id_position'],
                    ['field_type' => 'text', 'label' => 'Flight Number (if applicable)', 'name' => 'flight_number'],
                    ['field_type' => 'date', 'label' => 'Date of Duty', 'name' => 'date_of_duty'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Concern', 'name' => 'concern_type', 'options' => ['Fatigue Risk', 'Duty Time Exceedance', 'Minimum Rest Violation', 'Misconnection', 'Unclear Roster Info']],
                    ['field_type' => 'text', 'label' => 'Other Concern Type', 'name' => 'concern_type_other'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description of Concern', 'name' => 'concern_description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Was the Concern Resolved?', 'name' => 'concern_resolved', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Resolution Details / Action Taken by OCC', 'name' => 'resolution_details'],
                    ['field_type' => 'radio', 'label' => 'Follow-up Required?', 'name' => 'follow_up_required', 'options' => ['Yes', 'No']],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'text', 'label' => 'Contact Info (optional)', 'name' => 'contact_info'],
                ],
            ],
            [
                'name' => 'Disruption Safety Report',
                'category' => 'OCC',
                'description' => 'Report operational disruptions and safety impact.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Departure & Arrival Stations', 'name' => 'departure_arrival_stations'],
                    ['field_type' => 'text', 'label' => 'Scheduled Departure Time', 'name' => 'scheduled_departure_time'],
                    ['field_type' => 'text', 'label' => 'Actual Departure Time', 'name' => 'actual_departure_time'],
                    ['field_type' => 'checkbox', 'label' => 'Type of Disruption', 'name' => 'disruption_type', 'options' => ['Weather', 'Technical', 'Crew', 'ATC']],
                    ['field_type' => 'text', 'label' => 'Other Disruption Type', 'name' => 'disruption_type_other'],
                    ['field_type' => 'textarea', 'label' => 'Description of Safety Impact', 'name' => 'safety_impact_description'],
                    ['field_type' => 'radio', 'label' => 'Was Safety Compromised?', 'name' => 'safety_compromised', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Details of Crew Actions or Concerns', 'name' => 'crew_actions_concerns'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Actions Taken', 'name' => 'immediate_actions_taken'],
                    ['field_type' => 'textarea', 'label' => 'Preventive/Corrective Recommendations', 'name' => 'recommendations'],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                    ['field_type' => 'text', 'label' => 'Department/Position', 'name' => 'department_position'],
                ],
            ],
            [
                'name' => 'Delay Root Cause Analysis',
                'category' => 'OCC',
                'description' => 'Analyze flight delay root causes.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'report_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Departure Airport', 'name' => 'departure_airport'],
                    ['field_type' => 'text', 'label' => 'Arrival Airport', 'name' => 'arrival_airport'],
                    ['field_type' => 'text', 'label' => 'Scheduled Departure Time', 'name' => 'scheduled_departure_time'],
                    ['field_type' => 'text', 'label' => 'Actual Departure Time', 'name' => 'actual_departure_time'],
                    ['field_type' => 'number', 'label' => 'Total Delay Duration (minutes)', 'name' => 'delay_duration_minutes'],
                    ['field_type' => 'radio', 'label' => 'Primary Cause', 'name' => 'primary_cause', 'options' => ['ATC', 'Weather', 'Technical', 'Ground Handling', 'Late Inbound', 'Catering', 'Crew']],
                    ['field_type' => 'text', 'label' => 'Other Primary Cause', 'name' => 'primary_cause_other'],
                    ['field_type' => 'radio', 'label' => 'Was It a Reactionary Delay?', 'name' => 'reactionary_delay', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Secondary/Contributing Factors (if any)', 'name' => 'contributing_factors'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'textarea', 'label' => 'Preventive Measures Recommended', 'name' => 'preventive_measures'],
                    ['field_type' => 'text', 'label' => 'Department Responsible for Follow-up', 'name' => 'department_responsible'],
                    ['field_type' => 'text', 'label' => 'Prepared By', 'name' => 'prepared_by'],
                ],
            ],
            // === TRAINING FORMS ===
            [
                'name' => 'Simulator Session Report',
                'category' => 'Training',
                'description' => 'Document simulator training sessions and evaluations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Session', 'name' => 'date_of_session', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Simulator Type', 'name' => 'simulator_type'],
                    ['field_type' => 'text', 'label' => 'Aircraft Type/Variant', 'name' => 'aircraft_type'],
                    ['field_type' => 'text', 'label' => 'Instructor Name', 'name' => 'instructor_name'],
                    ['field_type' => 'select', 'label' => 'Trainee Position', 'name' => 'trainee_position', 'options' => ['Captain', 'FO', 'Other']],
                    ['field_type' => 'select', 'label' => 'Type of Training', 'name' => 'training_type', 'options' => ['Recurrent', 'Initial', 'Upgrade', 'Check Ride']],
                    ['field_type' => 'checkbox', 'label' => 'Exercises Conducted', 'name' => 'exercises_conducted', 'options' => ['Normal Ops', 'Abnormal', 'Emergency', 'Instrument Procedures', 'Manual Handling']],
                    ['field_type' => 'text', 'label' => 'Other Exercises', 'name' => 'exercises_other'],
                    ['field_type' => 'select', 'label' => 'Technical Skill', 'name' => 'technical_skill', 'options' => ['Excellent', 'Good', 'Satisfactory', 'Unsatisfactory']],
                    ['field_type' => 'select', 'label' => 'CRM / Communication', 'name' => 'crm_communication', 'options' => ['Excellent', 'Good', 'Satisfactory', 'Unsatisfactory']],
                    ['field_type' => 'select', 'label' => 'Adherence to SOPs', 'name' => 'sop_adherence', 'options' => ['Yes', 'Partial', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Notes', 'name' => 'notes'],
                    ['field_type' => 'select', 'label' => 'Result', 'name' => 'result', 'options' => ['Pass', 'Fail', 'Repeat Needed']],
                    ['field_type' => 'textarea', 'label' => 'Instructor Remarks', 'name' => 'instructor_remarks'],
                    ['field_type' => 'signature', 'label' => 'Instructor Signature', 'name' => 'instructor_signature'],
                ],
            ],
            [
                'name' => 'Trainee Feedback Form',
                'category' => 'Training',
                'description' => 'Collect trainee feedback on training sessions.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Feedback ID', 'name' => 'feedback_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'feedback_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Trainee Name', 'name' => 'trainee_name'],
                    ['field_type' => 'text', 'label' => 'Course/Module Title', 'name' => 'course_module_title'],
                    ['field_type' => 'text', 'label' => 'Instructor Name(s)', 'name' => 'instructor_names'],
                    ['field_type' => 'radio', 'label' => 'Training Material Quality (1=Poor to 5=Excellent)', 'name' => 'rating_material_quality', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'radio', 'label' => 'Instructor Knowledge (1=Poor to 5=Excellent)', 'name' => 'rating_instructor_knowledge', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'radio', 'label' => 'Clarity of Explanations (1=Poor to 5=Excellent)', 'name' => 'rating_clarity', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'radio', 'label' => 'Engagement & Interaction (1=Poor to 5=Excellent)', 'name' => 'rating_engagement', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'radio', 'label' => 'Practical Relevance (1=Poor to 5=Excellent)', 'name' => 'rating_practical_relevance', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'radio', 'label' => 'Time Management (1=Poor to 5=Excellent)', 'name' => 'rating_time_management', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'textarea', 'label' => 'What did you like most?', 'name' => 'liked_most'],
                    ['field_type' => 'textarea', 'label' => 'What should be improved?', 'name' => 'improvements'],
                    ['field_type' => 'textarea', 'label' => 'Any other feedback or suggestions?', 'name' => 'other_feedback'],
                    ['field_type' => 'radio', 'label' => 'Would you recommend this training?', 'name' => 'would_recommend', 'options' => ['Yes', 'No']],
                    ['field_type' => 'signature', 'label' => 'Trainee Signature (optional)', 'name' => 'trainee_signature'],
                ],
            ],
            [
                'name' => 'Training Observation Report',
                'category' => 'Training',
                'description' => 'Document training session observations.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Observation', 'name' => 'date_of_observation', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Observer Name', 'name' => 'observer_name'],
                    ['field_type' => 'text', 'label' => 'Position', 'name' => 'observer_position'],
                    ['field_type' => 'select', 'label' => 'Training Session Type', 'name' => 'session_type', 'options' => ['Classroom', 'Simulator', 'OJT', 'Other']],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'text', 'label' => 'Instructor Name', 'name' => 'instructor_name'],
                    ['field_type' => 'number', 'label' => 'Number of Trainees Observed', 'name' => 'trainees_observed'],
                    ['field_type' => 'text', 'label' => 'Subject / Module Observed', 'name' => 'subject_module'],
                    ['field_type' => 'number', 'label' => 'Duration (hours)', 'name' => 'duration_hours'],
                    ['field_type' => 'radio', 'label' => 'Training Conducted As Per Syllabus?', 'name' => 'per_syllabus', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Classroom/Simulator Conditions Acceptable?', 'name' => 'conditions_acceptable', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Trainee Engagement', 'name' => 'trainee_engagement'],
                    ['field_type' => 'textarea', 'label' => 'Instructor Delivery & Clarity', 'name' => 'instructor_delivery'],
                    ['field_type' => 'textarea', 'label' => 'Materials & Tools Used', 'name' => 'materials_tools'],
                    ['field_type' => 'select', 'label' => 'Overall Impression', 'name' => 'overall_impression', 'options' => ['Excellent', 'Satisfactory', 'Needs Improvement']],
                    ['field_type' => 'textarea', 'label' => 'Suggested Improvements', 'name' => 'suggested_improvements'],
                    ['field_type' => 'signature', 'label' => 'Observer Signature', 'name' => 'observer_signature'],
                ],
            ],
            // === AIRPORT SAFETY FORMS ===
            [
                'name' => 'Risk Assessment Form (Airport-Specific)',
                'category' => 'Airport Safety',
                'description' => 'Airport-specific hazard identification and risk assessment.',
                'fields' => [
                    ['field_type' => 'textarea', 'label' => 'Description of Hazard', 'name' => 'hazard_description', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Source / Trigger', 'name' => 'source_trigger'],
                    ['field_type' => 'textarea', 'label' => 'Potential Consequences', 'name' => 'potential_consequences'],
                    ['field_type' => 'select', 'label' => 'Likelihood (1–5)', 'name' => 'likelihood', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'select', 'label' => 'Severity (1–5)', 'name' => 'severity', 'options' => ['1', '2', '3', '4', '5']],
                    ['field_type' => 'select', 'label' => 'Risk Level', 'name' => 'risk_level', 'options' => ['Low', 'Medium', 'High', 'Extreme']],
                    ['field_type' => 'text', 'label' => 'Matrix (Color-coded)', 'name' => 'risk_matrix'],
                    ['field_type' => 'textarea', 'label' => 'Existing Measures', 'name' => 'existing_measures'],
                    ['field_type' => 'textarea', 'label' => 'Additional Controls Proposed', 'name' => 'additional_controls'],
                    ['field_type' => 'text', 'label' => 'Responsible Person / Dept', 'name' => 'responsible_person_dept'],
                    ['field_type' => 'date', 'label' => 'Implementation Deadline', 'name' => 'implementation_deadline'],
                    ['field_type' => 'text', 'label' => 'Review Cycle', 'name' => 'review_cycle'],
                ],
            ],
            [
                'name' => 'Safety Observation Report',
                'category' => 'Airport Safety',
                'description' => 'Report safety observations and behaviors.',
                'fields' => [
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'observation_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'observation_time'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'textarea', 'label' => 'Description of Behavior / Condition', 'name' => 'description', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Risk Level', 'name' => 'risk_level', 'options' => ['Low', 'Medium', 'High']],
                    ['field_type' => 'radio', 'label' => 'Classification', 'name' => 'classification', 'options' => ['Unsafe Act', 'Unsafe Condition', 'Safe Behavior', 'Safety Suggestion']],
                    ['field_type' => 'radio', 'label' => 'Action Taken', 'name' => 'action_taken', 'options' => ['Immediate', 'Logged']],
                    ['field_type' => 'radio', 'label' => 'Feedback to Staff', 'name' => 'feedback_to_staff', 'options' => ['Yes', 'No']],
                ],
            ],
            [
                'name' => 'Ground Vehicle Incident Report',
                'category' => 'Airport Safety',
                'description' => 'Report ground vehicle incidents on the airside.',
                'fields' => [
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'incident_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'incident_time'],
                    ['field_type' => 'select', 'label' => 'Location', 'name' => 'location', 'options' => ['Ramp', 'Apron', 'Taxiway Crossing', 'Maintenance Road', 'Other']],
                    ['field_type' => 'radio', 'label' => 'Type of Incident', 'name' => 'incident_type', 'options' => ['Collision', 'Speeding', 'Brake Failure', 'Unauthorized Entry']],
                    ['field_type' => 'text', 'label' => 'Vehicle Type', 'name' => 'vehicle_type'],
                    ['field_type' => 'text', 'label' => 'Vehicle Make', 'name' => 'vehicle_make'],
                    ['field_type' => 'text', 'label' => 'Vehicle Reg No.', 'name' => 'vehicle_reg_no'],
                    ['field_type' => 'text', 'label' => 'Driver Name', 'name' => 'driver_name'],
                    ['field_type' => 'text', 'label' => 'Driver License', 'name' => 'driver_license'],
                    ['field_type' => 'text', 'label' => 'Shift', 'name' => 'driver_shift'],
                    ['field_type' => 'text', 'label' => 'Other Vehicle or Aircraft (if applicable)', 'name' => 'other_party'],
                    ['field_type' => 'textarea', 'label' => 'Witnesses (Names / Contact Info)', 'name' => 'witnesses'],
                    ['field_type' => 'textarea', 'label' => 'Full Narrative', 'name' => 'full_narrative', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Speed at Time of Incident', 'name' => 'speed_at_incident'],
                    ['field_type' => 'radio', 'label' => 'Was PPE Used?', 'name' => 'ppe_used', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Was Airside Driving Permit Valid?', 'name' => 'permit_valid', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Damages to Equipment', 'name' => 'damages_equipment'],
                    ['field_type' => 'textarea', 'label' => 'Damages to Personnel', 'name' => 'damages_personnel'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action (Medical, Reporting, Towing)', 'name' => 'immediate_action'],
                    ['field_type' => 'textarea', 'label' => 'Root Cause (if available)', 'name' => 'root_cause'],
                    ['field_type' => 'textarea', 'label' => 'Disciplinary Measures (if any)', 'name' => 'disciplinary_measures'],
                    ['field_type' => 'radio', 'label' => 'Corrective Action Logged', 'name' => 'corrective_action_logged', 'options' => ['Yes', 'No']],
                ],
            ],
            [
                'name' => 'Wildlife Strike Report',
                'category' => 'Airport Safety',
                'description' => 'Report wildlife strikes with expanded content.',
                'fields' => [
                    ['field_type' => 'date', 'label' => 'Date', 'name' => 'strike_date', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time', 'name' => 'strike_time'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'select', 'label' => 'Phase of Flight', 'name' => 'phase_of_flight', 'options' => ['Takeoff', 'Landing', 'Climb-out', 'Other']],
                    ['field_type' => 'text', 'label' => 'Aircraft Type', 'name' => 'aircraft_type'],
                    ['field_type' => 'text', 'label' => 'Operator', 'name' => 'operator'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Runway in Use', 'name' => 'runway_in_use'],
                    ['field_type' => 'text', 'label' => 'Species (Identified / Unknown)', 'name' => 'species'],
                    ['field_type' => 'number', 'label' => 'Number Struck', 'name' => 'number_struck'],
                    ['field_type' => 'text', 'label' => 'Body Part Hit', 'name' => 'body_part_hit', 'placeholder' => 'Engine, Nose, Windshield, etc.'],
                    ['field_type' => 'text', 'label' => 'Visibility Conditions', 'name' => 'visibility_conditions'],
                    ['field_type' => 'radio', 'label' => 'Any Immediate Damage?', 'name' => 'immediate_damage', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Aircraft Downtime Required?', 'name' => 'downtime_required', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'FOD Clearance?', 'name' => 'fod_clearance', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Wildlife Control Team Alerted?', 'name' => 'wildlife_team_alerted', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Area Inspected After Incident?', 'name' => 'area_inspected', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Photos / ATC Recording Notes', 'name' => 'attachments_notes'],
                ],
            ],
            [
                'name' => 'Runway/Taxiway Hazard Report',
                'category' => 'Airport Safety',
                'description' => 'Report hazards on runways and taxiways.',
                'fields' => [
                    ['field_type' => 'date', 'label' => 'Date Detected', 'name' => 'date_detected', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time Detected', 'name' => 'time_detected'],
                    ['field_type' => 'text', 'label' => 'Exact Location', 'name' => 'exact_location'],
                    ['field_type' => 'radio', 'label' => 'Type of Hazard', 'name' => 'hazard_type', 'options' => ['FOD', 'Surface Damage', 'Lighting', 'Spills']],
                    ['field_type' => 'text', 'label' => 'Detected By (Name / Role)', 'name' => 'detected_by'],
                    ['field_type' => 'radio', 'label' => 'Area Closed or Marked?', 'name' => 'area_closed_marked', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Hazard Removed?', 'name' => 'hazard_removed', 'options' => ['Yes', 'No']],
                    ['field_type' => 'radio', 'label' => 'Maintenance Notified?', 'name' => 'maintenance_notified', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Corrective Action Description', 'name' => 'corrective_action_description'],
                    ['field_type' => 'text', 'label' => 'Person Responsible', 'name' => 'person_responsible'],
                    ['field_type' => 'date', 'label' => 'Timeline for Resolution', 'name' => 'resolution_timeline'],
                    ['field_type' => 'select', 'label' => 'Hazard Status', 'name' => 'hazard_status', 'options' => ['Open', 'Mitigated', 'Closed']],
                ],
            ],
            // === MRO QUALITY FORMS ===
            [
                'name' => 'Supplier Evaluation Report',
                'category' => 'MRO Quality',
                'description' => 'Evaluate suppliers for parts, services, and tools.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Supplier Name', 'name' => 'supplier_name', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Category', 'name' => 'category', 'options' => ['Parts', 'Services', 'Tools']],
                    ['field_type' => 'date', 'label' => 'Evaluation Date', 'name' => 'evaluation_date', 'required' => true],
                    ['field_type' => 'textarea', 'label' => 'Criteria Evaluated', 'name' => 'criteria_evaluated', 'placeholder' => 'Timeliness, Quality, Compliance'],
                    ['field_type' => 'text', 'label' => 'Score / Rating', 'name' => 'score_rating'],
                    ['field_type' => 'textarea', 'label' => 'Findings', 'name' => 'findings'],
                    ['field_type' => 'select', 'label' => 'Approval Status', 'name' => 'approval_status', 'options' => ['Approved', 'Conditional', 'Rejected']],
                    ['field_type' => 'text', 'label' => 'Evaluator Name', 'name' => 'evaluator_name'],
                    ['field_type' => 'select', 'label' => 'Review Frequency', 'name' => 'review_frequency', 'options' => ['Annual', 'Biannual']],
                ],
            ],
            [
                'name' => 'Tool & Equipment Calibration Report',
                'category' => 'MRO Quality',
                'description' => 'Track tool and equipment calibration.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Equipment ID', 'name' => 'equipment_id', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Type / Name', 'name' => 'equipment_type_name'],
                    ['field_type' => 'date', 'label' => 'Last Calibration Date', 'name' => 'last_calibration_date'],
                    ['field_type' => 'date', 'label' => 'Due Date', 'name' => 'due_date'],
                    ['field_type' => 'radio', 'label' => 'Calibration Result', 'name' => 'calibration_result', 'options' => ['Pass', 'Fail']],
                    ['field_type' => 'radio', 'label' => 'Service Provider', 'name' => 'service_provider', 'options' => ['Internal', 'External']],
                    ['field_type' => 'textarea', 'label' => 'Notes', 'name' => 'notes'],
                    ['field_type' => 'signature', 'label' => 'Supervisor Signature', 'name' => 'supervisor_signature'],
                ],
            ],
            [
                'name' => 'Non-Conformance Report (NCR) – MRO Quality',
                'category' => 'MRO Quality',
                'description' => 'Report non-conformances in MRO quality processes.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'NCR Number', 'name' => 'ncr_number', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date Identified', 'name' => 'date_identified', 'required' => true],
                    ['field_type' => 'textarea', 'label' => 'Description of Non-Conformance', 'name' => 'description', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Department / Process', 'name' => 'department_process'],
                    ['field_type' => 'select', 'label' => 'Severity', 'name' => 'severity', 'options' => ['Minor', 'Major']],
                    ['field_type' => 'textarea', 'label' => 'Root Cause', 'name' => 'root_cause'],
                    ['field_type' => 'textarea', 'label' => 'Corrective Action', 'name' => 'corrective_action'],
                    ['field_type' => 'text', 'label' => 'Person Responsible', 'name' => 'person_responsible'],
                    ['field_type' => 'date', 'label' => 'Closure Date', 'name' => 'closure_date'],
                ],
            ],
            [
                'name' => 'Work Order Quality Checklist',
                'category' => 'MRO Quality',
                'description' => 'Quality checklist for work orders.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Work Order Number', 'name' => 'work_order_number', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Aircraft Reg. / Component', 'name' => 'aircraft_component'],
                    ['field_type' => 'select', 'label' => 'Maintenance Type', 'name' => 'maintenance_type', 'options' => ['Scheduled', 'Unscheduled']],
                    ['field_type' => 'text', 'label' => 'Technician(s)', 'name' => 'technicians'],
                    ['field_type' => 'textarea', 'label' => 'Items Checked', 'name' => 'items_checked'],
                    ['field_type' => 'radio', 'label' => 'Deviations Found', 'name' => 'deviations_found', 'options' => ['Yes', 'No']],
                    ['field_type' => 'textarea', 'label' => 'Remarks', 'name' => 'remarks'],
                    ['field_type' => 'signature', 'label' => 'QA Sign-Off', 'name' => 'qa_signoff'],
                ],
            ],
            [
                'name' => 'Internal Audit Report – MRO Quality',
                'category' => 'MRO Quality',
                'description' => 'Internal audit report for MRO quality department.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Audit Number', 'name' => 'audit_number', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Department Audited', 'name' => 'department_audited'],
                    ['field_type' => 'text', 'label' => 'Auditor Name(s)', 'name' => 'auditor_names'],
                    ['field_type' => 'date', 'label' => 'Audit Date(s)', 'name' => 'audit_date'],
                    ['field_type' => 'textarea', 'label' => 'Audit Scope', 'name' => 'audit_scope', 'placeholder' => 'Process, tools, personnel'],
                    ['field_type' => 'radio', 'label' => 'Non-conformities Found', 'name' => 'non_conformities_found', 'options' => ['Y', 'N']],
                    ['field_type' => 'textarea', 'label' => 'Non-conformities Details', 'name' => 'non_conformities_details'],
                    ['field_type' => 'textarea', 'label' => 'Observations', 'name' => 'observations'],
                    ['field_type' => 'textarea', 'label' => 'Recommendations', 'name' => 'recommendations'],
                    ['field_type' => 'textarea', 'label' => 'Follow-Up Actions', 'name' => 'follow_up_actions'],
                    ['field_type' => 'select', 'label' => 'Status', 'name' => 'status', 'options' => ['Open', 'Closed']],
                    ['field_type' => 'signature', 'label' => 'Signature', 'name' => 'signature'],
                ],
            ],
            // === GROUND SAFETY FORMS ===
            [
                'name' => 'Ground Safety Report (GSR)',
                'category' => 'Ground Safety',
                'description' => 'Report ground safety concerns and events.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Event', 'name' => 'time_of_event'],
                    ['field_type' => 'text', 'label' => 'Location', 'name' => 'location'],
                    ['field_type' => 'select', 'label' => 'Area of Operation', 'name' => 'area_of_operation', 'options' => ['Ramp', 'Gate', 'Baggage', 'Fueling', 'Catering', 'Other']],
                    ['field_type' => 'text', 'label' => 'Reporter Name & Position', 'name' => 'reporter_name_position'],
                    ['field_type' => 'text', 'label' => 'Type of Safety Concern', 'name' => 'safety_concern_type'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description', 'name' => 'detailed_description', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Personnel Involved', 'name' => 'personnel_involved'],
                    ['field_type' => 'text', 'label' => 'Contractor/3rd Party (if any)', 'name' => 'contractor_third_party'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Actions Taken', 'name' => 'immediate_actions_taken'],
                    ['field_type' => 'textarea', 'label' => 'Recommendations / Follow-up Actions', 'name' => 'recommendations_followup'],
                    ['field_type' => 'text', 'label' => 'Reported To (Name & Department)', 'name' => 'reported_to'],
                ],
            ],
            [
                'name' => 'Baggage Handling Issue Report',
                'category' => 'Ground Safety',
                'description' => 'Report baggage handling issues and mishandling.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Time of Event', 'name' => 'time_of_event'],
                    ['field_type' => 'text', 'label' => 'Airport/Station', 'name' => 'airport_station'],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'select', 'label' => 'Type of Issue', 'name' => 'issue_type', 'options' => ['Lost', 'Damaged', 'Mishandled', 'Offloaded', 'Delay']],
                    ['field_type' => 'text', 'label' => 'Passenger Involved (if known)', 'name' => 'passenger_involved'],
                    ['field_type' => 'number', 'label' => 'Number of Bags Affected', 'name' => 'bags_affected'],
                    ['field_type' => 'textarea', 'label' => 'Detailed Description', 'name' => 'detailed_description'],
                    ['field_type' => 'text', 'label' => 'Handled By (Name/Dept)', 'name' => 'handled_by'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Resolution Steps', 'name' => 'resolution_steps'],
                    ['field_type' => 'select', 'label' => 'Final Status', 'name' => 'final_status', 'options' => ['Resolved', 'Pending', 'Escalated']],
                ],
            ],
            [
                'name' => 'Turnaround Incident Report',
                'category' => 'Ground Safety',
                'description' => 'Report turnaround and ground handling incidents.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'text', 'label' => 'Flight Number', 'name' => 'flight_number'],
                    ['field_type' => 'text', 'label' => 'Aircraft Registration', 'name' => 'aircraft_registration'],
                    ['field_type' => 'text', 'label' => 'Scheduled Turnaround Time', 'name' => 'scheduled_turnaround_time'],
                    ['field_type' => 'text', 'label' => 'Actual Turnaround Time', 'name' => 'actual_turnaround_time'],
                    ['field_type' => 'select', 'label' => 'Type of Incident', 'name' => 'incident_type', 'options' => ['Late Catering', 'Fuel Delay', 'Ground Power', 'Cleaning', 'Other']],
                    ['field_type' => 'text', 'label' => 'Time of Occurrence', 'name' => 'time_of_occurrence'],
                    ['field_type' => 'text', 'label' => 'Responsible Party', 'name' => 'responsible_party'],
                    ['field_type' => 'textarea', 'label' => 'Description of Incident', 'name' => 'incident_description'],
                    ['field_type' => 'number', 'label' => 'Delay (minutes)', 'name' => 'delay_minutes'],
                    ['field_type' => 'textarea', 'label' => 'Immediate Action Taken', 'name' => 'immediate_action_taken'],
                    ['field_type' => 'radio', 'label' => 'Follow-up Required', 'name' => 'followup_required', 'options' => ['Yes', 'No']],
                    ['field_type' => 'text', 'label' => 'Reported By', 'name' => 'reported_by'],
                ],
            ],
            [
                'name' => 'Ramp Equipment Defect Report',
                'category' => 'Ground Safety',
                'description' => 'Report defects in ramp equipment.',
                'fields' => [
                    ['field_type' => 'text', 'label' => 'Report ID', 'name' => 'report_id', 'required' => true],
                    ['field_type' => 'date', 'label' => 'Date of Report', 'name' => 'date_of_report', 'required' => true],
                    ['field_type' => 'select', 'label' => 'Equipment Type', 'name' => 'equipment_type', 'options' => ['Tug', 'Belt Loader', 'GPU', 'Air Start Unit', 'Other']],
                    ['field_type' => 'text', 'label' => 'Equipment ID/Number', 'name' => 'equipment_id_number'],
                    ['field_type' => 'text', 'label' => 'Operator Name', 'name' => 'operator_name'],
                    ['field_type' => 'date', 'label' => 'Date of Defect', 'name' => 'defect_date'],
                    ['field_type' => 'text', 'label' => 'Time of Defect', 'name' => 'defect_time'],
                    ['field_type' => 'text', 'label' => 'Location (Ramp/Parking Bay)', 'name' => 'location'],
                    ['field_type' => 'textarea', 'label' => 'Description of Defect', 'name' => 'defect_description', 'required' => true],
                    ['field_type' => 'radio', 'label' => 'Removed from Service', 'name' => 'removed_from_service', 'options' => ['Yes', 'No']],
                    ['field_type' => 'text', 'label' => 'Notified To (Maintenance/Ground Ops)', 'name' => 'notified_to'],
                    ['field_type' => 'textarea', 'label' => 'Temporary Fix (if any)', 'name' => 'temporary_fix'],
                    ['field_type' => 'radio', 'label' => 'Further Follow-up Required', 'name' => 'followup_required', 'options' => ['Yes', 'No']],
                ],
            ],
        ];

        foreach ($templates as $templateData) {
            $fields = $templateData['fields'];
            unset($templateData['fields']);

            $template = FormTemplate::firstOrCreate(
                ['name' => $templateData['name'], 'category' => $templateData['category']],
                $templateData
            );

            // Skip if template already has fields (avoid duplicates on re-seed)
            if ($template->formTemplateFields()->exists()) {
                continue;
            }

            foreach ($fields as $order => $fieldData) {
                $fieldData['order'] = $order;
                $fieldData['required'] = $fieldData['required'] ?? false;
                $fieldData['options'] = $fieldData['options'] ?? null;
                $fieldData['placeholder'] = $fieldData['placeholder'] ?? null;

                FormTemplateField::create([
                    'form_template_id' => $template->id,
                    'field_type' => $fieldData['field_type'],
                    'label' => $fieldData['label'],
                    'name' => $fieldData['name'],
                    'placeholder' => $fieldData['placeholder'],
                    'required' => $fieldData['required'],
                    'options' => $fieldData['options'],
                    'order' => $fieldData['order'],
                ]);
            }
        }
    }
}
